##### Sortal - Sign Based Teleportation #####
### Made by Lolmewn ###
### Please consider a small donation @ sybren_gjaltema@msn.com ###
### If you need help you can always open a conversation with me ###

#What happens on Startup#
showWhenWarpGetsLoaded: true

#Use of certain plugins#
plugins:
    usePermissions: true
    useVault: true
    
#Messages#
no-permissions: You do not have permissions to do that!
warpCreateNameForgotten: You must give a name to your warp!
warpCreateCoordsForgotten: You must specify the coords for this warp!
warpDeleteNameForgotten: You must specify the name of the warp!
nameInUse: Sorry, that name is in use!
moneyPayed: This has cost you MONEY!
warpCreated: Warp WARPNAME set up!
notEnoughMoney: You do not have enough money to do that!
warpDeleted: Warp WARPNAME deleted!
warpDoesNotExist: This warp does not exist!
notAplayer: You must be a player to use this command!

#Databases - if both false, flatfile will be used#
#NOTE: SQLite and MySQL ARE BROKEN#
useSQLite: false
useMySQL: false
MySQL:
    username: root
    password: root
    database: minecraft
    host: localhost

#Some other settings, if price is 0 no Money Plugin will be used#
warpCreatePrice: 0
warpUsePrice: 0
##If the player didn't specify the coords, use his (same as 'this')
ifNoCoordsUsePlayerCoords: true
##If the sign contains this line, it will be seen as a [Sortal] sign. ##
##If this is not [Sortal], both this setting and [Sortal] will be seen as [Sortal] signs.##
signContains: [Sortal]
    
#Updating and current version#
auto-update: true
version: 4.0
